name: CI/CD for Puppeteer Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gconf-service \
            libasound2 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgconf-2-4 \
            libnspr4 \
            libnss3 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            libxrandr2

      - name: Install npm dependencies
        run: npm install

      - name: Run Puppeteer tests
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: npm test
