name: CI/CD for Puppeteer Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image with Puppeteer and Node.js
      - name: Build Docker image
        run: |
          docker build -t puppeteer-test .

      # Run tests inside the Docker container
      - name: Run Puppeteer tests inside Docker
        run: |
          docker run --rm puppeteer-test npm test

      # Send Slack Notification for Success
      - name: Send Slack Notification - Success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":white_check_mark: Puppeteer tests passed successfully! 🎉",
            "attachments": [
              {
                "color": "#36a64f",
                "fields": [
                  { "title": "Branch", "value": "${{ github.ref_name }}", "short": true },
                  { "title": "Commit", "value": "${{ github.sha }}", "short": true }
                ]
              }
            ]
          }' $SLACK_WEBHOOK_URL

      # Send Slack Notification for Failure
      - name: Send Slack Notification - Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":x: Puppeteer tests failed! 💥",
            "attachments": [
              {
                "color": "#ff0000",
                "fields": [
                  { "title": "Branch", "value": "${{ github.ref_name }}", "short": true },
                  { "title": "Commit", "value": "${{ github.sha }}", "short": true },
                  { "title": "Error Logs", "value": "Check logs in GitHub Actions for details." }
                ]
              }
            ]
          }' $SLACK_WEBHOOK_URL

